name: mintly
description: "A Money management app using Flutter, Hive and Riverpod"

publish_to: 'Playstore'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  connectivity_wrapper: ^1.2.8
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.1.0
  flutter_svg: ^2.2.3
  go_router: ^17.0.1
  hive_ce: ^2.18.0
  hive_ce_flutter: ^2.3.4
  package_info_plus: ^9.0.0
  riverpod_annotation: ^4.0.0

dev_dependencies:
  build_runner: ^2.10.5
  flutter_gen_runner: ^5.12.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  hive_ce_generator: ^1.10.0
  riverpod_generator: ^4.0.0+1

flutter_gen:
  integrations:
    image: true
    flutter_svg: true
    rive: true
    lottie: true

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/on_boarding/
    - assets/general/
    - assets/bottom_nav/
    # - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
